### ISSUE TITLE
time.tzset() not working on Synology python 3.7/3.8

### ISSUE THREAD

**Issue by CoenWhite** [markruys/gw2pvo#53]
Hi Mark, thanks for keeping this great package alive. It has been succesfully uploading our solar data now for almost two years. gw2pvo has been running on a Synology NAS without problems, but after a recent python update (3.8) I had to reinstall.
This gave me access to some of the recent updates of the script: so no more 'Success'/'success' stuff, and a config file: nice!

However, the City command now leads to errors on my installation, so I've had to remove it and then the script works smoothlessly again. 

According to the output and some testing it is related to python's time module, which should support the tzset() function because synology runs a version of linux, but somehow it is not included:

```
gw2pvo --config gw2pvo.cfg --date 2020-11-22 --log debug
DEBUG    gw2pvo version 1.3.6
Traceback (most recent call last):
  File "/volume1/@appstore/python3/bin/gw2pvo", line 8, in <module>
    sys.exit(run())
  File "/var/packages/python3/target/lib/python3.7/site-packages/gw2pvo/__main__.py", line 196, in run
    time.tzset()
AttributeError: module 'time' has no attribute 'tzset'
```
I've verified this with both the 'synocommunity python' (3.7.7) and standard synology python package (3.8.2)... it's really strange because afaik tzset() should be part of any linux python installation...
```
cat /proc/version
Linux version 4.4.59+ (root@build3) (gcc version 4.9.3 20150311 (prerelease) (crosstool-NG 1.20.0) ) #25426 SMP PREEMPT Wed Jul 8 03:21:29 CST 2020
```
This might not be right place to dive into this issue, but maybe it will show if other people have the same problem, and the workaround for now to leave the city out, if your timezone is set correctly (haven't found out if it stops darksky from working).

**Comment by brad-newman** [comment]
ever get this sorted? experiencing this now in an app I'm building
